name: Mirror */* tags from Bitnami

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.MIRROR_APP_ID }}
          private-key: ${{ secrets.MIRROR_APP_PRIVATE_KEY }}
          permission-workflows: write
          permission-contents: write
          permission-metadata: read

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          token: ${{ steps.app-token.outputs.token }}

      - name: Fetch tags from public Bitnami repo
        env:
          SOURCE_REPO: https://github.com/bitnami/charts.git
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add bitnami https://x-access-token:${GITHUB_TOKEN}@${SOURCE_REPO#https://}
          git fetch bitnami main
          git fetch --tags --prune bitnami

      - name: Push main branch to current repository
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Pushing main branch..."
          git push https://x-access-token:${APP_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git refs/remotes/bitnami/main:refs/heads/main

      - name: Push only */* tags to current repository
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          TAGS=$(git tag -l '*/*')

          if [ -z "$TAGS" ]; then
            echo "No */* tags found to push."
            exit 0
          fi

          echo "Pushing tags: $TAGS"
          for TAG in $TAGS; do
            git push https://x-access-token:${APP_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git refs/tags/$TAG:refs/tags/$TAG
          done
